### ISSUE TITLE
hello, I got in trouble of install "SQLiteMigrationManager.swift" 

### ISSUE THREAD

**Issue by huFly** [garriguv/SQLiteMigrationManager.swift#18]
when i install "SQLiteMigrationManager.swift" by cocoapods : 
pod 'SQLiteMigrationManager.swift', '~> 0.3.0'
then:
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `SQLiteMigrationManager.swift (~> 0.3.0)` required by `Podfile`

Specs satisfying the `SQLiteMigrationManager.swift (~> 0.3.0)` dependency were found, but they required a higher minimum deployment target.

can you help me?  Thanks

**Comment by garriguv** [comment]
> they required a higher minimum deployment target.

`SQLiteMigrationManager.swift` requires a minimum deployment target of iOS 9.0. Looks like this could be 8.0 since `SQLite.swift` has a minimum deployment target of iOS 8.0. Pull requests are welcome!
