### ISSUE TITLE
Broken with Xcode 10.2

### ISSUE THREAD

**Issue by christopheblin** [garriguv/SQLiteMigrationManager.swift#29]
Because of https://github.com/stephencelis/SQLite.swift/issues/888, this project completely breaks.

Note that once the issue is fixed in SQLite.swift (with the patch I am going to provide with the issue), it works normally

**Comment by kroussevrb** [comment]
When is an update expected

**Comment by garriguv** [comment]
I’m on sabbatical until May. I might get to this in 10 days or so.

**Comment by sicaboy** [comment]
+1

**Comment by garriguv** [comment]
I have released version `0.6.0`, you should be good to go.

**Comment by ypopovych** [comment]
I released SQLite.swift 0.12.0. With Swift 5 support. You can use it for Swift 5
