### ISSUE TITLE
SQLite.swift dependency version does not compile on xcode 7.3 simulator

### ISSUE THREAD

**Issue by jaceee** [garriguv/SQLiteMigrationManager.swift#4]
I worked this issue arround creating a fork and setting SQLite.swift version to `~> 0.10.1`.

**Comment by PranKe01** [comment]
Yeah, an update would be nice :| Can't install SQLiteMigrationManager 0.0.5 with SQLite 0.10.1 and cocoapods.

**Comment by polarman3d** [comment]
+1 for an update here so we can build on the Simulator

**Comment by jaceee** [comment]
I've been using my fork for a while since I am working on a project that needs to ship very soon. Made PR since no work has been done on the matter.

**Comment by Fujikatoma** [comment]
An Update would be nice

**Comment by PranKe01** [comment]
Yes, please update so that we can use it with SQLite.swift 0.11.0 and Swift3 :)
