### ISSUE TITLE
Improve setup guide and example

### ISSUE THREAD

**Issue by rafaelclaycon** [garriguv/SQLiteMigrationManager.swift#42]
I just set up SQLiteMigrationManager.swift on a project and was a little confused about how to implement the migrations. What particularly puzzled me was the fact that SQL file migrations and Swift migrations don't need to be used together (contrary to the impression I got from the current setup guide - README - and project example).

I would like to contribute text to the README and code to the iOS example dir, but I've never contributed to an open source project before, so any guidance on how to do so is very much appreciated!

Thanks.

**Comment by garriguv** [comment]
Hey, thank you for the feedback. You're welcome to open a PR to try and improve the documentation. You can even do this on GitHub directly: 

![CleanShot 2022-09-18 at 21 44 12](https://user-images.githubusercontent.com/346164/190925560-c71d5d14-febd-449c-b68d-21b5616da98e.png)
