### ISSUE TITLE
update podspec to support SQLite.swift SQLCipher subspec

### ISSUE THREAD

**Issue by liyuan116** [garriguv/SQLiteMigrationManager.swift#45]
Hi Garriguv, I want to use Subspec in SQlite.Swift: SQLCipher, But SQLiteMigrationManager.Swift default  subspec is standard I submitted a pull https://github.com/garriguv/SQLiteMigrationManager.swift/pull/44   can you have a look？very thanks。

**Comment by garriguv** [comment]
That makes sense. I'll get the PR reviewed, merged, then will release a new version.

Nice work, thank you 👍
