### ISSUE TITLE
Migration changing column name not working below iOS version 13.0.

### ISSUE THREAD

**Issue by NitinKumarMck** [garriguv/SQLiteMigrationManager.swift#46]
I am using SQLite.Swift latest version 0.14.1 version and for i am using [SQLiteMigrationManager.swift].
above  iOS version 13.0 migration working as expected but below iOS version 13.0 migration are failing i don't know why. 
issue list: 
1. column name renaming 
2. drop column from table 

What m implemented let me share. 
struct V2:Migration {
    var version: Int64 = 2023_03_27_02_55_06
    let tableAccounts = Table(Database.TableName.tableAccounts) // Accounts Table
    let catalogDownloadDateFrench = Expression<Int>(AccountsColumn.catalogDownloadDateFrench)
    let itemCreatedDate = Expression<Int64>(OrderDetailsColumn.itemCreatedDate)
    func migrateDatabase(_ db: SQLite.Connection) throws {
        do {
            let schemaChanger = SchemaChanger(connection: db)
            try schemaChanger.alter(table: Database.TableName.tableAccounts, block: { tableAccounts in
                tableAccounts.rename(column: UserAccountsColumn.catalogDownloadDate, to: AccountsColumn.catalogDownloadDateEnglish)
            })
            try db.run(tableAccounts.addColumn(catalogDownloadDateFrench, defaultValue: 0))
        } catch {
            debugPrint("MIGRATION FAILED-------")
        }
    }
}

<img width="1135" alt="Screenshot 2023-04-04 at 1 28 20 PM" src="https://user-images.githubusercontent.com/119922446/229726679-90d97f08-676c-4c98-852a-48e335c01996.png">

**Comment by garriguv** [comment]
This appears to be a problem with the migration itself, not the migration manager, so I'm sorry but this looks like an issue with `SchemaChanger` or `SQLite`.
