### ISSUE TITLE
Xcode 16 Beta: Package does not compile; missing value: label in Expression call

### ISSUE THREAD

**Issue by rafaelschmitt-telus** [garriguv/SQLiteMigrationManager.swift#53]
## Build Information

- SQLiteMigrationManager.swift 0.8.1, main
- Xcode 16.0 Beta, macOS Sonoma 14.5
- Integrated using Swift Package Manager

## Issue

Just downloaded Xcode 16.0 Beta and tried running my app that uses SQLiteMigrationManager.swift. The following error is blocking the build:

![Screenshot 2024-06-11 at 10 33 05](https://github.com/garriguv/SQLiteMigrationManager.swift/assets/164226253/607cd5bd-9916-4504-97fa-d7ef41a1f904)

Steps to reproduce:
1. Start a new project.
2. Add SQLiteMigrationManager.swift.
3. Build.

**Comment by Svetoslav** [comment]
This should be fixed in https://github.com/garriguv/SQLiteMigrationManager.swift/pull/52

**Comment by brzzdev** [comment]
@garriguv Any chance of getting that merged and released, please?

**Comment by garriguv** [comment]
Just merged the PR. Sorry for the delay, I've been busy :)
