### ISSUE TITLE
Is the 0.8.3 version not submitted to CocoaPods Specs？

### ISSUE THREAD

**Issue by xiushaomin** [garriguv/SQLiteMigrationManager.swift#54]
https://github.com/CocoaPods/Specs/tree/master/Specs/5/1/6/SQLiteMigrationManager.swift

**Comment by xiushaomin** [comment]
@garriguv

**Comment by wendyliga** [comment]
@garriguv please help push the 0.8.3 podspec

**Comment by wendyliga** [comment]
in the meantime, use
```
pod "SQLiteMigrationManager.swift", :git => 'https://github.com/garriguv/SQLiteMigrationManager.swift.git', :tag => '0.8.3'
```

**Comment by xiushaomin** [comment]
Yes, now I am using tag. thanks @wendyliga. But still want author update podspec. :) @garriguv

**Comment by garriguv** [comment]
I'll update the podspec today.

**Comment by garriguv** [comment]
It's live: https://cocoapods.org/pods/SQLiteMigrationManager.swift

**Comment by xiushaomin** [comment]
thanks @garriguv
