### ISSUE TITLE
Make it Swift3 and SQLite.swift 0.11.0 compatible

### ISSUE THREAD

**Issue by PranKe01** [garriguv/SQLiteMigrationManager.swift#7]
I forked the branch and edited it, so it works with Swift3: https://github.com/PranKe01/SQLiteMigrationManager.swift

Anyway it would be great, if this library would be maintained by the developer :)

**Comment by jberkel** [comment]
@garriguv salut! long time no see :)

are you still working on this, or too busy with other things? (see related discussion here https://github.com/stephencelis/SQLite.swift/issues/526)

**Comment by garriguv** [comment]
Hey @jberkel and @PranKe01 . Sorry I haven't worked on this in a while (obviously). I'll have a look at the PR and build this week and get the library up to speed 😃

**Comment by garriguv** [comment]
Version `0.1.0` is now Swift 3 compatible.

The API isn't too great though, so there might be a `1.0.0` soonish.

**Comment by jberkel** [comment]
Thanks for your help! Haven't used your project, so can't comment on the API, but might need something like it soon.
