### ISSUE TITLE
Update Deployment Target

### ISSUE THREAD

**Issue by PranKe01** [garriguv/SQLiteMigrationManager.swift#9]
The migration manager got iOS 8.0 as target in the podspec. The current SQLite.swift package got 9.0. When building my project, I get ena error, that the target of the module SQLite.swift is 9.0 (because the migration manager is 8.0).

Please update the podspec =)

**Comment by sicaboy** [comment]
+1

**Comment by garriguv** [comment]
I've just released `0.2.0` which drops support for iOS 8
